package com.example.demo;

public enum TokenType {
    PROJECT, NAME, SEMICOLON, CONST, EQUALS, INTEGER_VALUE, VAR, COLON, INT, COMMA, ROUTINE,
    START, END, ASSIGN, ADD_SIGN, SUB_SIGN, MUL_SIGN, DIV_SIGN, MOD_SIGN, INPUT, OUTPUT,
    IF, LEFT_PAREN, RIGHT_PAREN, THEN, ELSE, ENDIF, LOOP, DO, NOT_EQUALS, LESS_THAN,
    LESS_THAN_EQUALS, GREATER_THAN, GREATER_THAN_EQUALS, DOT, SPACE, NEW_LINE, ERROR
}
